[pytest]

addopts = --html=report.html --base-url=https://demoqa.com --disable-warnings --browser=chromium --headed --slowmo=1000 --tracing=on
testpaths = tests
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*